### PR TITLE
Switch to S3 file field

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Review by brianhelba — APPROVED** [review]

**Comment by mgrauer** [comment]
Was it really this painless? That's great if so.

**Comment by brianhelba** [comment]
> Was it really this painless? That's great if so.

@mgrauer There are 3 more lines of code you need for a full install of S3FF, in `setup.py`, `settings.py`, `urls.py`, but those are already set up in the cookiecutter for us.

**Comment by zachmullen** [comment]
@mgrauer [this](https://github.com/girder/girder_web_components/commit/86c1cc5e1808bfe456c5dc7d6e8b33684d15ab98) was the front-end change required.

**Comment by mgrauer** [comment]
Good to know, thanks to you both for the info.

**Pull request merged**
